<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[3]=array(0,2,1,'5qGI5L6L5Lqn5ZOB');
$cfg_Cs[4]=array(3,2,1,'5omL5py65bqU55So');
$cfg_Cs[5]=array(3,2,1,'572R56uZ6K6+6K6h');
$cfg_Cs[6]=array(3,2,1,'5bmz6Z2i6K6+6K6h');
$cfg_Cs[8]=array(2,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[9]=array(2,1,1,'5Lqn5ZOB5Yqo5oCB');
$cfg_Cs[10]=array(2,1,1,'6KGM5Lia55+l6K+G');
$cfg_Cs[11]=array(0,1,1,'6aaW6aG15Zyw5Zu+');
?>