<!-- Blog Post -->
            	<div class="blog-post">
                
                	<div class="type-date">                    
                    	<div class="blog-type"><img src="/moke8/images/blog-quote.png" alt=""></div>
                        <div class="blog-date"><h5>[field:pubdate function='strftime("%m-%d",@me)'/]</h5></div>                    
                    </div>
                	
                    
                    
                    <!-- Post Content -->
                	<div class="post-content">

                            
                        <h3 class="blog-title"><a href="blog-post.html" class="external">Standard blog post with gallery</a></h3>
                        
                        <p class="blog-meta">Posted by <a href="#">Admin</a> | <a href="#">Design</a> | <a href="#">5 Comments</a></p>
                        
                        <div class="blog-border"></div>
                        
                        <div class="blog-content">
                        
                            <p>Nullam ornare, sem in malesuada sagittis, quam sapien ornare massa, id pulvinar quam augue vel orci. Praesent leo orci, cursus ac malesuada et, sollicitudin eu erat. Pellentesque ornare mi vitae sem consequat ac bibendum neque adipiscing. Donec tellus nunc, tincidunt sed faucibus a, mattis eget purus.</p>
                            
                        </div>
                        
                        <a href="blog-post.html" class="newave-button medium color external">Read More</a>
                        
                        <hr>
                    
                    </div>
                	<!--/Post Content -->
                    
                </div>
            	<!-- Blog Post -->