<div class="portfolio-item one-four one-one [field:typename/] web">
            
            <div class="portfolio-image">
                <img src="[field:picname/]" alt="[field:fulltitle/]">
            </div>
            
            <a title="Starbucks Coffee" rel="prettyPhoto[galname]" href="[field:arcurl/]">
            <div class="project-overlay">              
                <div class="project-info">
                    <div class="zoom-icon"></div>
                    <h4 class="project-name">[field:title/]</h4>
                    <p class="project-categories">[field:typename/]</p>	
                </div>
            </div>
            </a>
              
            </div>