
<field:name itemname="名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:email itemname="E-MAIL" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:con itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:con>

<field:phone itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>
