<!-- Blog Post -->
            	<div class="blog-post">
                
                	<div class="type-date">                    
                    	<div class="blog-type"><img src="/moke8/images/blog-quote.png" alt=""></div>
                        <div class="blog-date"><h5>[field:pubdate function=MyDate('M',@me)/]</h5><h5>[field:pubdate function='strftime("%d")'/]</h5></div>                    
                    </div>
                	
                    
                    
                    <!-- Post Content -->
                	<div class="post-content">

                            
                        <h3 class="blog-title"><a href="[field:arcurl/]" class="external">[field:title/]</a></h3>
                        
                        <p class="blog-meta">Posted by [field:writer/] | [field:typename/] </p>
                        
                        <div class="blog-border"></div>
                        
                        <div class="blog-content">
                        
                            <p>[field:infos/]...</p>
                            
                        </div>
                        
                        <a href="[field:arcurl/]" class="newave-button medium color external">Read More</a>
                        
                        <hr>
                    
                    </div>
                	<!--/Post Content -->
                    
                </div>
            	<!-- Blog Post -->