<div class="blogitem">
	<div class="blogimage">
		<div class="image_frame">
			
			<a href="#![field:arcurl/]" class="nolink">
				<!-- Recomended width 350px  -->
				<img src="[field:picname/]" width="350" height="225" />
			</a>
			<div class="hoverWrapperBg"></div>
		
		</div>
	</div>
	<div class="blogcontent">
		<h3>[field:title/]</h3>
		<div class="meta-links">
			<!-- Tooltip descriptions are defined in rel attributes -->
			<a class="meta-author nolink" href="#![field:arcurl/]" rel="[field:writer/]"></a>
			<a class="meta-comments nolink" href="#![field:arcurl/]" rel="[field:click/] views"></a>
			<a class="meta-tags nolink" href="#![field:arcurl/]" rel="tag1, tag2"></a>
		</div>
		<p>
		[field:infos/]
		</p>
		<a class="morelink" href="#![field:arcurl/]">more</a>
	</div>
	<div class="blogTop" style="padding-top:8px;"><hr/><a class="nolink" href="javascript:void(0);">TOP</a></div>
	<div class="clearfix"></div>
</div>