<?php
$z[0]=Array("field","",23,53);
$z[0][4]['name']="typename";
$z[1]=Array("global","",138,164);
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("field","",253,283);
$z[2][4]['name']="typename";
$z[3]=Array("field","",339,360);
$z[3][4]['name']="content";
$z[4]=Array("global","",448,474);
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("global","",1035,1061);
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("global","",1612,1638);
$z[6][4]['name']="cfg_cmspath";

?>