<div class="portfolio-item one-four [field:typename/] web" style="position: absolute; left: 0px; top: 0px; width: 355px;">
            
            <div class="portfolio-image">
                <img src="[field:picname/]" alt="[field:fulltitle/]" height="271" width="370">
            </div>
            
            <a title="[field:title/]" href="[field:arcurl/]">
            <div class="project-overlay">              
                <div class="project-info">
                    <div class="zoom-icon"></div>
                    <h4 class="project-name">[field:title/]</h4>
                    <p class="project-categories">[field:typename/]</p>	
                </div>
            </div>
            </a>
              
            </div>