<li>
	<div class="image_frame">
		<a href="[field:picname/]" class="nolink">
			<img src="[field:picname/]" width="290" height="186" />
		</a>
		<div class="hoverWrapperBg"></div>
		<div class="hoverWrapper">
			<h3>[field:title/]</h3>
			<div class="enter-text">[field:infos/]</div>
			<a class="link" href="#![field:arcurl/]"></a>
			<a class="modal nolink" href="javascript:void(0);"></a>
		</div>
	</div>
</li>