<?php
$z[0]=Array("global","",1620,1640);
$z[0][4]['name']="cfg_x";
$z[1]=Array("global","",1641,1661);
$z[1][4]['name']="cfg_y";
$z[2]=Array("global","",2921,2943);
$z[2][4]['name']="cfg_lxr";
$z[3]=Array("global","",2953,2974);
$z[3][4]['name']="cfg_qq";
$z[4]=Array("global","",2988,3015);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",3024,3044);
$z[5][4]['name']="cfg_x";
$z[6]=Array("global","",3045,3065);
$z[6][4]['name']="cfg_y";

?>