<?php
$z[0]=Array("field","",20,50);
$z[0][4]['name']="typename";
$z[1]=Array("list","\r\n<li>\r\n	<div class=\"image_frame\">\r\n		<a href=\"[field:picname/]\" class=\"nolink\">\r\n			<img src=\"[field:picname/]\" width=\"290\" height=\"186\" />\r\n		</a>\r\n		<div class=\"hoverWrapperBg\"></div>\r\n		<div class=\"hoverWrapper\">\r\n			<h3>[field:title/]</h3>\r\n			<div class=\"enter-text\">[field:infos/]</div>\r\n			<a class=\"link\" href=\"#![field:arcurl/]\"></a>\r\n			<a class=\"modal nolink\" href=\"javascript:void(0);\"></a>\r\n		</div>\r\n	</div>\r\n</li>\r\n",148,643);
$z[1][4]['pagesize']="4";
$z[1][4]['titlelen']="35";
$z[1][4]['infolen']="200";
$z[2]=Array("pagelist","",781,852);
$z[2][4]['listitem']="info,index,end,pre,next,pageno";
$z[2][4]['listsize']="5";

?>